print('Welcome to the Tip Calculator. Stop Counting on your fingers in public today!')
total = input("What was your total bill?\n")
people = input("How many people to split the bill?\n")
tip = input("What percentage would you like to tip?\n")
divide = (int(total) / int(people))
percent = (float(tip) / 100)
finalTip = (divide * percent)
dollarAmount = (round(finalTip, 2))
totalBill = (float(finalTip) + float(divide))
print("Your tip should be: " + str(dollarAmount) + " for a total of " + str(totalBill))
